### ISSUE TITLE
Unfortunately, FetChat has stopped

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#18]
I had one occurrence when clicking on the FetChat icon that the app stopped responding and i got a "Unfortunately, FetChat has stopped".

http://i.imgur.com/BKrwHBF.png

SirBis
Samsung Note 5

**Comment by kistitan** [comment]
Hi SirBis,

Thank you for your feedback.
We uploaded a new version that we think solved the issue.
Please feel free to reopen the issue if it would occur again.

Please keep in mind the new version has a different app name so you should uninstall the current version, otherwise you will have two app parallely and the old will keep producing the issue.

Best regards

**Comment by Cayce7** [comment]
I just downloaded the app for the first time and I'm getting the "unfortunately fetlife had stopped" error.
