### ISSUE TITLE
distribute the APK as a GitHub release instead of as a file in source control.

### ISSUE THREAD

**Issue by smiller171** [fetlife/fetlife-android#69]
Distributing the apk in source control is really poor practice for a lot of reasons. Should distribute with GitHub releases. I can assist with this if desired

**Comment by reneklacan** [comment]
👍 I agree that we should do this

**Comment by JohnBaku** [comment]
👍 Cool!!! 

https://help.github.com/articles/creating-releases/

**Comment by smiller171** [comment]
@JohnBaku I could take this on and integrate with CircleCI so that builds happen on commit, and releases on a GH tag. should be pretty trivial

**Comment by JohnBaku** [comment]
@smiller171 thanks for the offer... that is nice of you! It's @kistitan project so it's up to him... what say you @kistitan ?

**Comment by kistitan** [comment]
Hi smiler,

About the suggestion: it is no brainer.
Current solution was only a temporary workaround to make the apk accessible for people who are interested in it even before the first release.

Until the app was not fully functional (at least with the minimum expected functionality) we (actually I) did not want to make it as an official release.

Our first official release will be 1.0 and will be launched via GH releases in a few days.


About the suggestion with CircleCI:
It is awesome and feels very good people like feel like contributing.
I am very happy about it. :)

I am also convinced that we would need something like that soon.
I don't know the exact process of CircleCI in details however there are some questions that makes it a bit more complex trivial.

One is the signing of the apk. Signature of the releases should be the same otherwise the if users should uninstall and reinstall the apk at each time when it is change. 

Currently the key we use for signing is not public. 
It might not be a problem to make it public, but we should have a discussion about it first.
Same goes for exception logging and push related keys (their current version are public but we also should take into consideration if we keep it like that)

For example one typical use case that we want to avoid is that somebody abuse the open source code and modify it locally to simple log the user's login name and password. 
We cannot avoid this situation, but what we can do is to keep our own signing key secret so as long as the apk has the same signature as our official releases the users can trust in our app.

Again: keeping the official release links safe can be good enough protection but it is still a topic that worth a discussion (internal and external too of course).

So before saying a definite yes, one contribution would be pretty helpful to check out how the signature process would work with you suggested solution and how could be some variables kept private.

Thanks you for your help and suggestions again :)

**Comment by smiller171** [comment]
Thanks @kistitan 

As far as releases goes, GH releases lets you mark iterations as pre-release, so it's still an effective tool.

I hadn't considered signing keys, which is a major consideration, and simply cannot be public. I'll do some research and report back with my findings.

**Comment by smiller171** [comment]
@kistitan It looks like the best practice if building in CircleCi would be to store the key encrypted in source control, and keep the decryption key as a secure var in CircleCi. You would want to keep testing external PRs disabled in Circle to prevent external actors from exposing the decryption key with a PR.

Alternatively Travis-CI allows you to continue to use external PRs, while only decrypting the secure var if it's an internal PR

**Comment by smiller171** [comment]
I'll start testing this and submit a PR when I have all but the signing key working, and will provide instructions for that

**Comment by smiller171** [comment]
gonna create a new github account though before I fork this

**Comment by BlackFun171** [comment]
all right, here's the new me

**Comment by JohnBaku** [comment]
@kistitan 

> Until the app was not fully functional (at least with the minimum expected functionality) we (actually I) did not want to make it as an official release.

You going to continue to hold that against me! :-p

@kistitan and @smiller171 we already use CircleCI for fetlife-web so if you need any help getting it setup maybe @fetlife/engineering can lend a hand.

**Comment by BlackFun171** [comment]
@JohnBaku I'm pretty good with CircleCI, less strong with Android

I'm getting hung up on an error here, is this where it's looking for the keys?

```
Service.java:174: error: cannot find symbol
                BuildConfig.CLIENT_ID,
                           ^
  symbol:   variable CLIENT_ID
  location: class BuildConfig
/home/ubuntu/fetlife-android/fetlife/src/main/java/com/bitlove/fetlife/model/service/FetLifeApiIntentService.java:175: error: cannot find symbol
                BuildConfig.CLIENT_SECRET,
                           ^
  symbol:   variable CLIENT_SECRET
  location: class BuildConfig
/home/ubuntu/fetlife-android/fetlife/src/main/java/com/bitlove/fetlife/model/service/FetLifeApiIntentService.java:176: error: cannot find symbol
                BuildConfig.REDIRECT_URL,
                           ^
  symbol:   variable REDIRECT_URL
  location: class BuildConfig
/home/ubuntu/fetlife-android/fetlife/src/main/java/com/bitlove/fetlife/model/service/FetLifeApiIntentService.java:247: error: cannot find symbol
                BuildConfig.CLIENT_ID,
                           ^
  symbol:   variable CLIENT_ID
  location: class BuildConfig
/home/ubuntu/fetlife-android/fetlife/src/main/java/com/bitlove/fetlife/model/service/FetLifeApiIntentService.java:248: error: cannot find symbol
                BuildConfig.CLIENT_SECRET,
                           ^
  symbol:   variable CLIENT_SECRET
  location: class BuildConfig
/home/ubuntu/fetlife-android/fetlife/src/main/java/com/bitlove/fetlife/model/service/FetLifeApiIntentService.java:249: error: cannot find symbol
                BuildConfig.REDIRECT_URL,
                           ^
  symbol:   variable REDIRECT_URL
  location: class BuildConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors
 FAILED
```

**Comment by BlackFun171** [comment]
also, what's the purpose of the "Experiment" dir? Is this the same project with experimental stuff, or is it entirely different?

**Comment by kistitan** [comment]
@BlackFun171 
It is not the signing yet.

BuildConfig is a file that is generated by the Android BuildProcess based on the build.gradle file.
So based on the error the file is not generated or you are trying to make a release build instead of debug build.

Client Id and Client Secrets are used for identify the app by the server. 
These values available publicly only for debug version.

**Comment by kistitan** [comment]
Hi, 

First app release is published as as a github release.

I close this issue now, and open later a new one for build automatization.
